import { defineConfig } from "tsdown";
import { buildEngine } from "./src/preview/bundle.ts";

export default defineConfig({
	entry: [
		"src/index.ts",
		"src/effects/index.ts",
		"src/audio/index.ts",
		"src/signals/index.ts",
		"src/renderer/index.ts",
		"src/fonts/index.ts",
		"src/preview/index.ts",
		"src/project/index.ts",
	],
	format: ["esm"],
	clean: true,
	// The live preview's browser engine, shipped prebuilt in dist/preview-engine.
	onSuccess: () => buildEngine("dist/preview-engine"),
	dts: { resolve: [/^@framefields\//] },
	target: "es2022",
	noExternal: [/^@framefields\//],
	external: [
		/^node:/,
		/^@napi-rs\//,
		/^@resvg\//,
		/^@mediabunny\//,
		/^@lottiefiles\//,
		"mediabunny",
		"onnxruntime-node",
		"skia-canvas",
		"fontkit",
		/^d3-/,
		"webgpu",
		"yoga-layout",
		"zod",
		"sharp",
		"gsap",
		"earcut",
		"fflate",
		"gifuct-js",
		"nanoid",
		"pino",
		"file-type",
		"dotenv",
	],
});
