import { defineConfig } from "tsdown";

export default defineConfig({
	entry: [
		"src/index.ts",
		"src/effects/index.ts",
		"src/audio/index.ts",
		"src/signals/index.ts",
		"src/renderer/index.ts",
		"src/fonts/index.ts",
	],
	format: ["esm"],
	clean: true,
	dts: { resolve: [/^@gitframes\//] },
	target: "es2022",
	noExternal: [/^@gitframes\//],
	external: [
		/^node:/,
		/^@napi-rs\//,
		/^@resvg\//,
		/^@mediabunny\//,
		/^@lottiefiles\//,
		"mediabunny",
		"onnxruntime-node",
		"skia-canvas",
		"fontkit",
		"chartgpu",
		"webgpu",
		"yoga-layout",
		"zod",
		"sharp",
		"gsap",
		"earcut",
		"fflate",
		"gifuct-js",
		"nanoid",
		"pino",
		"file-type",
		"dotenv",
	],
});
