#!/usr/bin/env -S tsx --conditions development
// Generates the static list of built-in node renderers that @gitframes/renderer
// registers at startup. Static `import()` specifiers let the published bundle
// (packages/gitframes, `noExternal: /^@gitframes\//`) carry every renderer, so
// rendering does not depend on a `nodes/` directory existing on disk.
//
//   pnpm run generate:node-renderers             # write the generated file
//   pnpm run generate:node-renderers -- --check  # fail if the committed file is stale
//
// Source of truth: nodes/<node>/package.json (`gitframes` block, `./renderer`
// export, `gatewai.enabled`). Output (never edit by hand):
//   packages/renderer/src/generated/node-renderers.ts
//   packages/renderer/package.json `dependencies` (one entry per node below)
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { loadNodeManifests } from "../packages/renderer/src/node-manifest.ts";

const repoRoot = path.resolve(
	path.dirname(fileURLToPath(import.meta.url)),
	"..",
);
const NODES_DIR = path.join(repoRoot, "nodes");
const RENDERER_PKG = path.join(
	repoRoot,
	"packages",
	"renderer",
	"package.json",
);
const OUT_FILE = path.join(
	repoRoot,
	"packages",
	"renderer",
	"src",
	"generated",
	"node-renderers.ts",
);
const check = process.argv.includes("--check");

const manifests = loadNodeManifests(NODES_DIR).filter(
	(m) => m.enabled && m.rendererExports,
);

const entries = manifests.map((m) => {
	const ops = [m.type, ...m.aliases].map((op) => JSON.stringify(op)).join(", ");
	return [
		"\t{",
		`\t\tpackageName: ${JSON.stringify(m.packageName)},`,
		`\t\tops: [${ops}],`,
		`\t\tload: () => import(${JSON.stringify(`${m.packageName}/renderer`)}),`,
		"\t},",
	].join("\n");
});

const source = `// @generated by scripts/generate-node-renderers.mts — do not edit.
// Source of truth: nodes/*/package.json (\`gitframes\`, \`./renderer\` export).
// Regenerate with \`pnpm run generate:node-renderers\`.
import type { NodeRendererPlugin } from "@gitframes/node-sdk";

export interface BuiltinNodeRenderer {
	packageName: string;
	/** Declared op followed by its aliases. */
	ops: readonly string[];
	load: () => Promise<{ default?: NodeRendererPlugin }>;
}

export const BUILTIN_NODE_RENDERERS: readonly BuiltinNodeRenderer[] = [
${entries.join("\n")}
];
`;

// Each renderer must be a dependency so pnpm links it and turbo builds it first.
const pkg = JSON.parse(fs.readFileSync(RENDERER_PKG, "utf-8"));
const deps: Record<string, string> = { ...pkg.dependencies };
for (const name of Object.keys(deps)) {
	if (name.startsWith("@gitframes/node-") && name !== "@gitframes/node-sdk") {
		delete deps[name];
	}
}
for (const m of manifests) deps[m.packageName] = "workspace:*";
pkg.dependencies = Object.fromEntries(
	Object.entries(deps).sort(([a], [b]) => a.localeCompare(b)),
);
const pkgSource = `${JSON.stringify(pkg, null, "\t")}\n`;

const outputs: [string, string][] = [
	[OUT_FILE, source],
	[RENDERER_PKG, pkgSource],
];

if (check) {
	const stale = outputs.filter(
		([file, content]) =>
			!fs.existsSync(file) || fs.readFileSync(file, "utf-8") !== content,
	);
	if (stale.length > 0) {
		console.error(
			`Stale: ${stale.map(([f]) => path.relative(repoRoot, f)).join(", ")}. Run \`pnpm run generate:node-renderers\`.`,
		);
		process.exit(1);
	}
	console.log(`node renderers up to date (${manifests.length} nodes)`);
} else {
	fs.mkdirSync(path.dirname(OUT_FILE), { recursive: true });
	for (const [file, content] of outputs) fs.writeFileSync(file, content);
	console.log(`wrote ${manifests.length} node renderers`);
}
